#!/usr/bin/env python3
"""Human-readable dump of race_node_catalog.json -> NODE_CATALOG.md"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
cat = json.loads((HERE / "race_node_catalog.json").read_text(encoding="utf-8"))

lines = ["# RacingV2 node catalog (mined)", "",
         "Source: 14 car graphs from `Saves\\RacingV2\\*.txt`.",
         "Generated by `mine_race_graphs.py`; do not hand-edit.", "",
         "`modifier` = whatever the node stores. For **dropdown nodes it is an INDEX**",
         "(no label text in Racing saves, unlike tennis); for **Float nodes it is the VALUE**.",
         "Header counts = node uses across all graphs.", ""]
for kind, v in cat.items():
    lines.append(f"## {kind}  ({v['count']}x, {len(v['files'])} graphs)")
    if v["modifiers"]:
        lines.append("")
        lines.append("| modifier / label | uses |")
        lines.append("|---|---|")
        for m, c in v["modifiers"].items():
            lines.append(f"| `{m}` | {c} |")
    if v["data_keys"]:
        lines.append("")
        lines.append("data keys: " + ", ".join(f"`{k}`" for k in v["data_keys"]))
    lines.append("")

(HERE / "NODE_CATALOG.md").write_text("\n".join(lines), encoding="utf-8")
print("wrote NODE_CATALOG.md", len(lines), "lines")

# Focused report: the Racing* API + transform/position sensors
focus = [k for k in cat if k.startswith("RacingV2") or k in (
    "RelativePosition", "HitInfo", "Distance", "Stat", "ConstructVector3",
    "Vector3Split", "AddVector3", "DotProduct", "CrossProduct", "GetRotation",
    "SetThrottle", "SetSteering", "SphereCast", "RayCast")]
print("\n=== Racing API surface ===")
for k in focus:
    v = cat[k]
    print(f"\n{k} ({v['count']}x)")
    for m, c in v["modifiers"].items():
        print(f"    {m}   x{c}")
